FROM node:22.16.0-alpine

ARG PORT=3000
ARG WEBSOCKET_URI='localhost:3001'
ENV PORT=${PORT}
ENV WEBSOCKET_URI=${WEBSOCKET_URI}

RUN mkdir /usr/web-app
WORKDIR /usr/web-app

COPY package.json package.json
COPY pnpm-lock.yaml pnpm-lock.yaml

COPY ./client ./

RUN npm install -g pnpm@latest
RUN pnpm install

CMD ["node", "./webserver.js"]
