FROM node:22.16.0-alpine

ARG PORT=3000
ENV PORT=${PORT}

RUN mkdir /usr/websocket-app
WORKDIR /usr/websocket-app

COPY package.json package.json
COPY pnpm-lock.yaml pnpm-lock.yaml

COPY ./server ./

RUN npm install -g pnpm@latest
RUN pnpm install

CMD ["node", "./websocket-server.js"]
